server:
  port: 0

spring:
  application:
    name: EXAM

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${random.int}