server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  application:
    name: CONFIG
  security:
    user:
      name: username
      password: password